config/routes.rb
Rails.application.routes.draw do
  resources :offers do
    collection do
      get 'page/:page', controller: 'offers', action: 'index'
    end
  end
  root 'offers#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :offers
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :company
  has_and_belongs_to_many :skills

  enum mode: [:full_time, :part_time, :freelance, :internship]

  validates :title, presence: true

  default_scope { order('updated_at DESC') }

  self.per_page = 10

  def human_mode
    I18n.t "offers.modes.#{mode}"
  end
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_and_belongs_to_many :offers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    @offers = Offer.paginate(page: params[:page])
  end

  def show
    @offer = Offer.find(params[:id])
  end

  def edit
    @offer = Offer.find(params[:id])
  end

  def update
    @offer = Offer.find(params[:id])
    respond_to do |format|
      if @offer.update(offers_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  private

  def offers_params
    params.require(:offer).permit(:title, :salary, :description, :mode, :company_id, :skill_ids => [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper  
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jobfers</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <header>
        <h1>Jobfers</h1>
      </header>
      <section class="content">
        <%= yield %>
      </section>
    </div>
  </body>
</html>

app/views/offers/_form.html.erb
<%= simple_form_for @offer do |f| %>
  <%= f.input :title %>
  <%= f.input :mode, collection: Offer.modes.keys.map {|mode| [t(mode), mode]} %>
  <%= f.input :salary %>
  <%= f.input :description %>
  <%= f.association :company %>
  <%= f.association :skills, as: :check_boxes %>
  <%= f.button :submit %>
<% end %>

app/views/offers/edit.html.erb
<h2>Edit <%= @offer.title %> at <%= @offer.company.name %></h2>
<%= render 'form' %>

app/views/offers/index.html.erb
<h2>Offers</h2>

<%= will_paginate @offers %>

<ul class="offers">
  <% @offers.each do |offer| %>
    <li>
      <a href="<%= offer_path(offer) %>">
        <div><strong><%= offer.title %></strong> at <%= offer.company.name %></div>
        <div class="offer"><%= offer.human_mode %></div>
      </a>
    </li>
    <br>
  <% end %>
</ul>

app/views/offers/show.html.erb
<div class="title">
  <h2><%= @offer.title %></h2>
  <h4><%= @offer.human_mode %></h4>

  <ul>
    <li>Empresa: <%= @offer.company.name %></li>
    <li>Salario: <%= number_to_currency(@offer.salary) %> CLP</li>
  </ul>

  <p><%= @offer.description %></p>
</div>
<div class="edit">
  <%= link_to 'Editar', edit_offer_path(@offer) %>
</div>